apiVersion: v1
kind: Pod
metadata:
  name: pvc-loader
spec:
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: ace-bar-store
  containers:
  - name: loader
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: pvc-storage
